services:
  mmd-public:
    build:
      context: .
      dockerfile: apps/mmd-public/Dockerfile
    depends_on:
      - draft-api
      - db

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    depends_on:
      - draft-api
      - db

  draft-api:
    build:
      context: .
      dockerfile: apps/draft-api/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all']

volumes:
  db-data:
