services:
  mmd-public:
    build:
      context: .
      dockerfile: apps/mmd-public/Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - '${MAIN_PORT:-3000}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - draft-api
    healthcheck:
      test: ['CMD', 'node', 'scripts/healthcheck.js']
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 40s

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    ports:
      - '${ADMIN_PORT:-3001}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - draft-api
    healthcheck:
      test: ['CMD', 'node', 'scripts/healthcheck.js']
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 40s

  draft-api:
    build:
      context: .
      dockerfile: apps/draft-api/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT:-5432}/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    ports:
      - '${API_PORT:-4000}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    healthcheck:
      test: ['CMD', 'node', 'scripts/healthcheck.js']
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 40s

  text-analysis-service:
    build:
      context: ./apps/text-analysis-service
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - '${TEXT_ANALYSIS_PORT:-5555}:8000'
    volumes:
      - ./apps/text-analysis-service:/app
    healthcheck:
      test: ['CMD', 'python', 'scripts/healthcheck.js']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all']
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  db-data:
