services:
  main:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.nextjs
      args:
        - APP_NAME=main
    depends_on:
      - api
      - db

  admin:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.nextjs
      args:
        - APP_NAME=admin
    depends_on:
      - api
      - db

  api:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile.node
      args:
        - APP_NAME=api
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all']

volumes:
  db-data:
