services:
  mmd-public:
    image: marcusjoseph/mock-my-draft_mmd-public:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.mockmydraft.com/api
    ports:
      - '${MAIN_PORT:-3000}:3000'
    restart: always
    depends_on:
      - draft-api
      - db

  admin:
    image: marcusjoseph/mock-my-draft_admin:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.mockmydraft.com/api
    ports:
      - '${ADMIN_PORT:-3001}:3000'
    restart: always
    depends_on:
      - draft-api
      - db

  draft-api:
    image: marcusjoseph/mock-my-draft_draft-api:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT:-5432}/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    ports:
      - '${API_PORT:-4000}:3000'
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all']

volumes:
  db-data:
