services:
  mmd-public:
    build:
      dockerfile: apps/mmd-public/Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - '${MAIN_PORT:-3000}:3000'
    volumes:
      - .:/app
      - /app/node_modules

  admin:
    build:
      dockerfile: apps/admin/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT:-4000}/api
    ports:
      - '${ADMIN_PORT:-3001}:3000'
    volumes:
      - .:/app
      - /app/node_modules

  draft-api:
    build:
      dockerfile: apps/draft-api/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT:-5432}/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    ports:
      - '${API_PORT:-4000}:3000'
    volumes:
      - .:/app
      - /app/node_modules

  db:
    ports:
      - '${DB_PORT:-5432}:5432'
