FROM python:3.9-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY package.json package-lock.json nx.json ./
COPY . .

RUN npm install

RUN cd /app/apps/text-analysis-service
RUN poetry install --no-interaction --no-ansi

ENV PORT=3000
EXPOSE ${PORT}

CMD ["nx", "serve", "text-analysis-service"]


