name: Build and publish Docker images

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for affected projects
        run: |
          AFFECTED_PROJECTS=$(npx nx show projects --affected --select=projects --base=origin/main~1 --head=HEAD)
          echo "Affected projects: $AFFECTED_PROJECTS"
          for app in $AFFECTED_PROJECTS
          do
            echo "Building and pushing $app"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$app:$GITHUB_SHA -f apps/$app/Dockerfile .
            docker push ${{ secrets.DOCKER_USERNAME }}/$app:$GITHUB_SHA
            docker push ${{ secrets.DOCKER_USERNAME }}/$app:latest
          done
