name: Build and publish Docker images

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Rollback to previous version'
        required: false
        default: 'false'
      build:
        description: 'Build and push Docker images'
        required: false
        default: 'true'
      deploy:
        description: 'Deploy to VPS'
        required: false
        default: 'true'

jobs:
  build:
    if: github.event.pull_request.merged == true || (github.event_name == 'workflow_dispatch' && ${{ github.event.inputs.build == 'true' }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for affected projects
        env:
          REPO_PREFIX: 'mock-my-draft'
        run: |
          echo "Determining base and head commits..."
          if [[ "${{ github.event_name }}" == "pull_request" ]]
          then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            BASE_SHA=${{ github.event.before }}
            HEAD_SHA=${{ github.sha }}
          fi
          echo "Base commit: $BASE_SHA"
          echo "Head commit: $HEAD_SHA"

          echo "Fetching any missing objects..."
          git fetch --depth=1 origin $BASE_SHA
          git fetch --depth=1 origin $HEAD_SHA

          AFFECTED_PROJECTS=$(npx nx show projects --affected --select=projects --base=$BASE_SHA --head=$HEAD_SHA --verbose)
          echo "Affected projects: $AFFECTED_PROJECTS"
          BUILD_FAILED=0
          for app in $AFFECTED_PROJECTS
          do
            if ./scripts/build-and-push-docker.sh "$app" "${{ secrets.DOCKER_USERNAME }}" "$REPO_PREFIX" "$GITHUB_SHA"; then
              echo "Successfully built and pushed $app"
            else
              echo "Failed to build and push $app"
              BUILD_FAILED=1
            fi
          done

          if [ $BUILD_FAILED -ne 0 ]
          then
            echo "One or more builds/pushes failed"
            exit 1
          fi
        shell: bash

  deploy:
    if: github.event.pull_request.merged == true || (github.event_name == 'workflow_dispatch' && ${{ github.event.inputs.deploy == 'true' }})
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            # Create a sparse checkout of the repo if it doesn't exist
            if [ ! -d "/home/marcus/projects/mock-my-draft" ]; then
              mkdir -p /home/marcus/projects/mock-my-draft
              cd /home/marcus/projects/mock-my-draft
              git init
              git remote add origin git@github.com:schimizzimj/mock-my-draft.git
              git config core.sparseCheckout true
              echo "docker-compose.base.yml" >> .git/info/sparse-checkout
              echo "docker-compose.prod.yml" >> .git/info/sparse-checkout
              echo "scripts/deploy.sh" >> .git/info/sparse-checkout
              echo "scripts/rollback.sh" >> .git/info/sparse-checkout
            fi

            # Pull the latest changes
            cd /home/marcus/projects/mock-my-draft
            git pull origin main

            if [ ${{ github.event.inputs.rollback }} == 'true' ]; then
              chmod +x scripts/rollback.sh
              ./scripts/rollback.sh
            else
              # Deploy the latest changes
              chmod +x scripts/deploy.sh
              ./scripts/deploy.sh
            fi
